### ISSUE TITLE
Visual Studio Python 3.9 Pip Install works but package can't be used in a from...import statement

### ISSUE THREAD

**Issue by paul-cleverley** [fmalina/blocl-bnglatlon#6]
I get an unresolved import 'bng_latlon' with the following line:

from bng_latlon import OSGB36toWGS84

**Comment by paul-cleverley** [comment]
pip show returns the following:

PS C:\Python39> pip show bng_latlon
Name: bng-latlon
Version: 1.0.2
Summary: Converts british national grid (OSBG36) to lat lon (WGS84) and vice versa.
Home-page: https://github.com/fmalina/blocl-bnglatlon
Author: Hannah Fry, F. Malina
Author-email: hi@blocl.com
License: MIT License
Location: c:\python39\lib\site-packages
Requires:
Required-by:

**Comment by pedromorgan** [comment]
Can confirm.. just did a `pip install` and folder is there, but no files

**Comment by pedromorgan** [comment]
This commit is maybe the culprit 
https://github.com/fmalina/blocl-bnglatlon/commit/0c8a8909defcebc013811d02cb339337bdcfa47b

**Comment by milos-simic** [comment]
I'm experiencing the same issue.

**Comment by pedromorgan** [comment]
@fmalina U there ??

**Comment by fmalina** [comment]
This is now resolved and installation via pip works again. The way functions are imported slightly changed
