### ISSUE TITLE
No module named 'bng_latlon'

### ISSUE THREAD

**Issue by mateusbbvs** [fmalina/blocl-bnglatlon#7]
I installed it with "pip install bng-latlon" and the message says: Requirement already satisfied: bng-latlon in c:...

However, using on jupyter 
`from bng_latlon import OSGB36toWGS84`

I get: No module named 'bng_latlon' 

I tried `from bng_to_latlon import OSGB36toWGS84`
The same problem appears.

I installed other packages to test if it was all packages in my computer, but they are fine.

**Comment by fmalina** [comment]
Have you gotten this to work?

**Comment by fmalina** [comment]
I suggest `pip3 uninstall bng-latlon` and `pip3 install bng-latlon`

**Comment by mateusbbvs** [comment]
Thank you @fmalina !
It worked.
